### ISSUE TITLE
Property testing

### ISSUE THREAD

**Issue by christophebiocca** [pemistahl/grex#6]
There's three main properties that can be tested, and they should help catch bugs more easily:

- [x] For any set of input strings, the output string should be a syntactically valid regex (according to which syntax? For now I assumed the regex crate's). (PR: #4)
- [x] For any set of input strings, the output string when compiled as a regex (under which engine) should match every input string (PR: #7).
- [x] For any set of input strings, and any set of other strings disjoint from the first, the output string (when compiled as a regex) should not match any of the non-input strings (PR: #8).

These are reasonably easy to write as property tests, and together should cover the entire contract of this 1-function library.

**Comment by pemistahl** [comment]
This is actually a very good idea, @christophebiocca. Thanks for your input. :) I especially thank you for pointing me to the [quickcheck](https://crates.io/crates/quickcheck) crate. I wasn't aware that something like this exists for Rust. It is a perfect fit for my use case.

**Comment by pemistahl** [comment]
These property tests have been implemented in version 0.3.1. Closed.
